"""empty message

Revision ID: 5fedc8377821
Revises: 5b54de69c585
Create Date: 2019-07-21 19:56:58.418058

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5fedc8377821'
down_revision = '5b54de69c585'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('forecasts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('forecast', sa.Text(), nullable=True),
    sa.Column('time', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('locations_model', sa.Column('search_query', sa.String(length=256), nullable=True))
    op.create_unique_constraint(None, 'locations_model', ['formatted_query'])
    op.create_unique_constraint(None, 'locations_model', ['search_query'])
    op.drop_column('locations_model', 'name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('locations_model', sa.Column('name', sa.VARCHAR(length=256), nullable=True))
    op.drop_constraint(None, 'locations_model', type_='unique')
    op.drop_constraint(None, 'locations_model', type_='unique')
    op.drop_column('locations_model', 'search_query')
    op.drop_table('forecasts')
    # ### end Alembic commands ###
